# Generated by Django 4.0.1 on 2022-05-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='current_rate',
            new_name='current_rating',
        ),
    ]
